"""GitHub publish routes.

POST /projects/{project_id}/publish/github
  — Pushes all approved milestone code artifacts to a new GitHub repository.
  — Returns the repository URL and stores it as a "github_repo" artifact.
  — Requires GITHUB_TOKEN in settings.

GET /projects/{project_id}/publish/github
  — Returns the stored GitHub repo URL (if any) for this project.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.config import settings
from app.db.session import get_db

router = APIRouter(tags=["github"])


# ── Schemas ───────────────────────────────────────────────────────────────────

class PublishResponse(BaseModel):
    repo_url: str
    repo_full_name: str
    files_pushed: int
    already_existed: bool
    errors: list[str]


class GitHubStatusResponse(BaseModel):
    enabled: bool          # True when GITHUB_TOKEN is set
    repo_url: str | None   # URL of the last published repo, if any


# ── Routes ────────────────────────────────────────────────────────────────────

@router.post(
    "/projects/{project_id}/publish/github",
    response_model=PublishResponse,
    summary="Publish generated code to a new GitHub repository",
)
def publish_to_github(project_id: int, db: Session = Depends(get_db)):
    """Push all milestone code artifacts for this project to GitHub.

    Creates a new private repository under GITHUB_DEFAULT_ORG (or the
    authenticated user's account) and commits all generated code files.
    The resulting URL is stored as a `github_repo` artifact so it appears
    in the dashboard.

    Requires GITHUB_TOKEN to be set in the environment / .env file.
    """
    if not settings.GITHUB_TOKEN:
        raise HTTPException(
            status_code=422,
            detail=(
                "GITHUB_TOKEN is not configured. "
                "Set it in .env to enable GitHub publishing."
            ),
        )

    # Load project to get name
    from app.db.models import Project, Artifact
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    # Collect milestone code artifact paths
    artifacts = (
        db.query(Artifact)
        .filter(
            Artifact.project_id == project_id,
            Artifact.type == "milestone_code",
        )
        .order_by(Artifact.version)
        .all()
    )
    artifact_paths = [a.file_path for a in artifacts if a.file_path]

    # Generate a lightweight README as an extra file
    readme = _build_readme(project.name, len(artifact_paths))

    from app.services.github_publish import publish_project
    try:
        result = publish_project(
            project_id=project_id,
            project_name=project.name,
            artifact_paths=artifact_paths,
            extra_files={"README.md": readme},
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"GitHub API error: {exc}")

    # Persist repo URL as a "github_repo" artifact so the dashboard can link it
    _upsert_github_artifact(db, project_id, result.repo_url, result.repo_full_name)

    return PublishResponse(
        repo_url=result.repo_url,
        repo_full_name=result.repo_full_name,
        files_pushed=result.files_pushed,
        already_existed=result.already_existed,
        errors=result.errors,
    )


@router.get(
    "/projects/{project_id}/publish/github",
    response_model=GitHubStatusResponse,
    summary="Get GitHub publish status for a project",
)
def get_github_status(project_id: int, db: Session = Depends(get_db)):
    """Return whether GitHub publishing is configured and the last repo URL."""
    from app.db.models import Artifact
    artifact = (
        db.query(Artifact)
        .filter(
            Artifact.project_id == project_id,
            Artifact.type == "github_repo",
        )
        .order_by(Artifact.version.desc())
        .first()
    )
    repo_url = None
    if artifact and artifact.file_path:
        # We store the URL in file_path for github_repo artifacts
        repo_url = artifact.file_path

    return GitHubStatusResponse(
        enabled=bool(settings.GITHUB_TOKEN),
        repo_url=repo_url,
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _build_readme(project_name: str, file_count: int) -> str:
    return (
        f"# {project_name}\n\n"
        f"This repository contains {file_count} code file(s) generated by "
        "[AgentOS](https://github.com/anthropics/agentos).\n\n"
        "## Getting started\n\n"
        "Review each generated file, run the provided tests, and adapt to your "
        "infrastructure before deploying.\n"
    )


def _upsert_github_artifact(
    db: Session,
    project_id: int,
    repo_url: str,
    full_name: str,
) -> None:
    """Create or update the github_repo artifact row for this project."""
    from app.db.models import Artifact
    existing = (
        db.query(Artifact)
        .filter(Artifact.project_id == project_id, Artifact.type == "github_repo")
        .order_by(Artifact.version.desc())
        .first()
    )
    next_version = (existing.version + 1) if existing else 1

    artifact = Artifact(
        project_id=project_id,
        type="github_repo",
        version=next_version,
        # Reuse file_path to store the URL (no binary content needed)
        file_path=repo_url,
        content_type="text/plain",
        metadata_={"repo_full_name": full_name},
    )
    db.add(artifact)
    db.commit()
